rabbit:
    part-1:
        queue-name: 'part-1-queue-1'
    part-2:
        workload-range: 10
        queue-name: 'part-2-queue-1'
    part-3:
        exchange-name: 'part-3-ex-1'
    part-4:
        exchange-name: 'part-4-ex-1'
        warm-colors-queue-name: 'part-4-warm-colors-queue'
        cold-colors-queue-name: 'part-4-cold-colors-queue'
        neutral-colors-queue-name: 'part-4-neutral-colors-queue'
    part-5:
        topic-name: 'part-5-topic-1'
        logs-queue-name: 'part-5-logs-queue'
        events-queue-name: 'part-5-events-queue'
        payments-queue-name: 'part-5-payments-queue'
        mgmt-queue-name: 'part-5-mgmt-queue'
        auth-queue-name: 'part-5-auth-queue'

